### 강의 등록
POST http://localhost:8080/api/courses
Content-Type: application/json
CREATOR-ID: 1

{
  "title": "테스트",
  "description": "테스트 입니다.",
  "price": 1000,
  "capacity": 10,
  "startDate": "2026-04-16",
  "endDate": "2026-04-21"
}